services:
  pinepods-db:
    container_name: pinepods-db
    image: postgres:18
    environment:
      PGDATA: /var/lib/pgdata/pgdata
    volumes:
      - ./pgdata:/var/lib/pgdata
    #ports:
    #  - "5432:5432"
    restart: always
    env_file: 
      - db.env

  pinepods-valkey:
    container_name: pinepods-valkey
    image: valkey/valkey:8-alpine
    #ports:
    #  - "6379:6379"

  pinepods:
    container_name: pinepods
    image: madeofpendletonwool/pinepods:latest
    ports:
      - "8040:8040"
    environment:
      # Basic Server Info
      SEARCH_API_URL: 'https://search.pinepods.online/api/search'
      PEOPLE_API_URL: 'https://people.pinepods.online'
      HOSTNAME: 'http://pinepods.tyler-clark.com'
      
      # Valkey Settings
      VALKEY_HOST: pinepods-valkey
      VALKEY_PORT: 6379

      # Enable or Disable Debug Mode for additional Printing
      DEBUG_MODE: false
      PUID: 1000
      PGID: 1000

      # Add timezone configuration
      TZ: "America/Chicago"
    env_file:
      - pinepods.env
    volumes:
      # Mount the download and backup locations on the server
      - /mnt/public/Podcasts:/opt/pinepods/downloads
      - ./backups:/opt/pinepods/backups
    depends_on:
      - pinepods-db
      - pinepods-valkey
    labels:
      - traefik.enable=true
      - traefik.http.routers.pinepods-https.rule=Host(`pinepods.tyler-clark.com`)
      - traefik.http.routers.pinepods-https.tls=true
      - traefik.http.routers.pinepods-https.tls.certresolver=cloudflare
      - traefik.http.services.pinepods-https.loadbalancer.server.port=8040

networks:
  default:
    external: true
    name: frontend